language: python
sudo: false
os:
- linux
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- pip -q install -r requirements.txt
- pip -q install -r requirements-dev.txt
- pip -q install ipython || echo "optional skipped"
- pip -q install pytest-cache || echo "optional skipped"
- pip -q install unittest2 || echo "optional skipped"
- pip -q install ordereddict || echo "optional skipped"
- pip -q install coveralls
script:
- curl --silent -Lo travis_after_all.py https://raw.github.com/pycontribs/travis_after_all/master/travis_after_all.py && travis_wait python setup.py test
- export PACKAGE_VERSION=$(python -c "from jira.version import __version__; print(__version__)")
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeeded! PUBLISHING..."
        else
          echo "Some jobs failed"
        fi
      fi
  - coveralls
  - travis_wait python setup.py prerelease
  - python setup.py build_sphinx upload_docs sdist bdist_wheel
after_failure:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
          echo "All jobs failed"
        else
          echo "Some jobs failed"
        fi
      fi
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
branches:
  only:
  - master
notifications:
  hipchat: 7d72ba6ba0bf07248f17e0a6a1a899@DevOps
before_deploy:
  - echo "before deploy..."
deploy:
  - provider: releases
    api_key:
      - secure: "gr9iOcQjdoAyUAim6FWKzJI9MBaJo9XKfGQGu7wdPXUFhg80Rp6GLJsowP+aU94NjXM1UQlVHDAy627WtjBlLH2SvmVEIIr7+UKBopBYuXG5jJ1m3wOZE+4f1Pqe9bqFc1DxgucqE8qF0sC24fIbNM2ToeyYrxrS6RoL2gRrX2I="
    file: "dist/jira-$PACKAGE_VERSION.tar.gz"
    skip_cleanup: true
    on:
      condition: "$BUILD_LEADER = YES"
  - provider: pypi
    user: sorin
    password:
      secure: "E0cjANF7SLBdYrsnWLK8X/xWznqkF0JrP/DVfDazPzUYH6ynFeneyofzNJQPLTLsqe1eKXhuUJ/Sbl+RHFB0ySo/j/7NfYd/9pm8hpUkGCvR09IwtvMLgWKp3k10NWab03o2GOkSJSrLvZofyZBGR40wwu2O9uXPCb2rvucCGbw="
    distributions: "sdist bdist_wheel"
    on:
      condition: "$BUILD_LEADER = YES"
after_deploy:
  - echo "Now we only have to increase the version number, tag the changset and push..."
  - ./release.sh
